# Server Configuration
server.port=8080

# H2 Database in-memory with PostgreSQL compatibility mode
spring.datasource.url=jdbc:h2:mem:demo;MODE=PostgreSQL;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# SQL Initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# H2 Console (để trực quan hóa dữ liệu nếu cần)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# jOOQ Configuration
spring.jooq.sql-dialect=H2

# Logging
logging.level.org.jooq=INFO
logging.level.vn.tnteco.demo=DEBUG
